config/routes.rb
Rails.application.routes.draw do
  get 'reviews/new'
  devise_for :users
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  resources :stories, only: [:new, :create, :show, :index, :destroy] do
    resources :collabs, only: [:new, :create]
    member do
      put "like" => "stories#upvote"
      put "unlike" => "stories#downvote"
    end
    resources :reviews, only: [:new, :create]
   end
  resources :categories
  resources :profiles
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :stories
  has_one_attached :photo

  def to_label
    "#{self.genre}"
  end
end

app/models/collab.rb
class Collab < ApplicationRecord
  belongs_to :user
  belongs_to :story
  has_many_attached :photos
  has_rich_text :rich_content
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :story
  belongs_to :user
end

app/models/story.rb
class Story < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many_attached :photos
  has_rich_text :rich_content
  has_many :collabs
  acts_as_votable
  has_many :reviews, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :stories
  has_one_attached :photo
  has_many :collabs
  acts_as_voter
  has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :username, :photo])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :username, :photo])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @stories = Story.select { |story| story.category_id == @category.id}
  end
end

app/controllers/collabs_controller.rb
class CollabsController < ApplicationController
  before_action :set_story, only: %i[new create]
  def new
    @collab = Collab.new
  end

  def create
    @story = Story.find(params[:story_id])
    @collab = Collab.new(collab_params)
    @collab.story = @story
    @collab.user = current_user
    @collab.save
    redirect_to story_path(@story)
  end

  def collab_params
    params.require(:collab).permit(:rich_content, :story_id)
  end

  def set_story
    @story = Story.find(params[:story_id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @stories = Story.all
    if user_signed_in?
      @user = User.find(current_user.id)
    end
    @categories = Category.all
  end

  def index
    @stories = Story.all
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find(params[:id])
    @user_stories = @user.stories
    @user_collabs = @user.collabs
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def new
    @story = Story.find(params[:story_id])
    @review = Review.new
  end

  def create
    @story = set_story
    @review = Review.new(review_params)
    @review.story = @story
    @review.user = current_user
    if @review.save
      redirect_to story_path(@story), notice: "Review Successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def set_story
    @story = Story.find(params[:story_id])
  end

  def review_params
    params.require(:review).permit(:comment)
  end

end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
    if params[:query].present?
      sql_subquery = "title ILIKE :query OR synopsis ILIKE :query"
      @stories = @stories.where(sql_subquery, query: "%#{params[:query]}%")
    end
  end

  def show
    @story = Story.find(params[:id])
    @collab = Collab.new
    @review = Review.new
    @stories = Story.all
   
  end

  def new
    @story = Story.new
  end

  def create
    @story = Story.new(story_params)
    @story.user = current_user
    if
    @story.save
    redirect_to story_path(@story)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @story = Story.find(params[:id])
    if current_user == @story.user
    @story.destroy
    end
    redirect_to stories_path, status: :see_other
  end

  def story_params
    params.require(:story).permit(:title, :rich_content, :genre, :category_id, :synopsis, photos: [])
  end

  def upvote
    @story = Story.find(params[:id])
    @story.upvote_from current_user
    redirect_to story_path(@story)
  end

  def downvote
    @story = Story.find(params[:id])
    @story.downvote_from current_user
    redirect_to story_path(@story)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/categories/index.html.erb
<div class="category-container">
<h1>All genres</h1>
<div class="category-card-container">
<% @categories.each do |category| %>
            <a href="<%= category_path(category.id) %>" class="category-card" >
              <%= category.genre  %>
            </a>
<% end %>
</div>
</div>

app/views/categories/show.html.erb
<div>
  <div class="idx-content">
    <div>
      <div class="infos-n-path">
      <h5><strong>Most recent</strong></h5>
      <a href="<%= categories_path %>" class="genres-txt-idx"><h5><strong>All categories</strong></h5></a>
      </div>
      <div class="stories-idx-cat">
        <% @stories.each do |story| %>
          <a href="<%= story_path(story.id)%>" class="story-card-idx">
            <%= cl_image_tag story.photos.first.key, class:"image-card-idx" %>
            <div class="story-info-idx">
              <h3 class="story-title-hp"><%= story.title %></h3>
              <p><%= story.synopsis %></p>
            </div>
          </a>
        <% end %>
      </div>
    </div>
    <div>
      <div class="recs-idx">
        <h2 class="text-center">Top <%= @category.genre %> picks</h2>
        <div class="stories-top-recs">
        <% @stories.sample(5).each do |story| %>
            <a href="<%= story_path(story.id)%>" class="story-card-idx-rec">
              <%= cl_image_tag story.photos.first.key, class:"image-card-idx-rec" %>
              <div class="story-info-idx-recs">
                <%= story.title %>
              </div>
            </a>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cowrite</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= render "shared/navbar" %>
    <%= render "shared/flashes" %>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
  </head>

  <body>

    <%= yield %>
    <%= render "shared/footer" %>
       <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="banner_notepad.PNG">
  <div class="banner-text">
    <h1>Welcome to  <strong>Co-Write</strong></h1>
      <h5>The home of creative<h5>
        <h5>writing collaborations<h5>
             <!-- Element to contain animated typing -->
      <span id="element"></span>

      <!-- Load library from the CDN -->
      <script src="https://unpkg.com/typed.js@2.1.0/dist/typed.umd.js"></script>

      <!-- Setup and start animation! -->
      <script class="typewriter">
        var typed = new Typed('#element', {
         class: "typo", strings:  ['Pick a story', 'Have a read', 'Write a chapter', 'Collaborate with others', 'Find your inspiration'],
          typeSpeed: 60,
          loop: true,

        });
      </script>

  </div>
</div>

  <div class="search-wrapper">
        <%= form_with url: stories_path, method: :get, class: "d-flex" do %>
          <%= text_field_tag :query,
              params[:query],
              class: "form-control",
              placeholder: "Discover a story..."
          %>
        <%= submit_tag "Search", name: "", class: "btn-search" %>
  <% end %>
  </div>
<div class="home-container">
  <div class="home-page-content">
    <div class="top-stories">
      <h4>Top stories</h4>
      <div class="stories-cards">

        <% @stories.each do |story| %>
          <a href="<%= story_path(story.id)%>" class="story-card-hp">
            <%= cl_image_tag story.photos.first.key, class:"image-card-hp" %>
            <div class="story-info-hp">
              <h3 class="story-title-hp"><%= story.title %></h3>
              <p><%= story.synopsis %></p>
            </div>
          </a>
        <% end %>
      <p><a href="<%= stories_path %>"class="create-button">Find inspiration </a></p>
      </div>
    </div>

    <div class="genres-wis">
      <h3><a href="<%= new_story_path %>" class="create-button" >
        Add a new story!</a></h3>
      <div class="categories-card-hp" >
        <a href="<%= categories_path %>" class="pb-2 genres-txt"><h3>Genres</h3></a>
        <div class="categories-cards-hp">
          <% @categories.each do |category| %>
              <a href="<%= category_path(category.id) %>" class="category-card-hp" >
              <%= category.genre  %>
            </a>
          <% end %>
        </div>
      </div>
      <div class="wic">
        <h3>What is CoWrite</h3>
        <p>CoWrite allows you to create, edit, like, and collaborate onto stories of your choosing, to help inspire and hopefully cure your writer’s block, getting your creative juices flowing.</p>
      </div>
    </div>
  </div>
</div>

app/views/pages/new.html.erb
<h1><%= New Story! %></h1>

app/views/profiles/show.html.erb
<section class="h-100 gradient-custom-2">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-25 col-xl-20">
        <div class="card">
          <div class="rounded-top text-white d-flex flex-row" style="background-image: url(<%= image_path 'green_banner.webp'%>)" >
            <div class="ms-4 mt-5 d-flex flex-column" style="width: 150px;">
                <% if @user.photo.attached? %>
                <%= cl_image_tag @user.photo.key, style:"width: 150px; z-index: 1" %>
                <% else %>
                <%= image_tag "blankprofile.png",style:"width: 150px; z-index: 1"%>
                <% end %>
                <% if @user == current_user %>
              <%= link_to edit_user_registration_path do %>
             <i class="fa fa-edit" style="font-size:24px;color:white"></i>
            <% end %>
            <% end %>
            </div>
            <div class="ms-3" style="margin-top: 130px;">
              <h4><%= @user.first_name %> <%= @user.last_name %></h4>
            </div>
          </div>

          <div class="p-4 text-black">
            <div class="d-flex justify-content-between text-center py-1">
              <div>
               <h4>My Stories</h4>
               <div class="profilestories">

                  <% @user_stories.each do |story| %>
                  <%= link_to story.title, story_path(story)  %>
                  <% end %>
               </div>
              </div>
              <div class="px-3">
                      <h4> My Collaborations </h4>
                      <% @user_collabs.each do |collab| %>
                      <p><%= link_to collab.story.title, story_path(collab.story)  %></p>

                    <% end %>
              </div>
            </div>
          </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/reviews/new.html.erb
<h1>New review</h1>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<footer>
  <div class="footer">
    <div class="row ">
      <div>
        <a href="#"><i class="fa fa-facebook"></i></a>
        <a href="#"><i class="fa fa-instagram"></i></a>
        <a href="#"><i class="fa fa-youtube"></i></a>
        <a href="#"><i class="fa fa-twitter"></i></a>
      </div>
    </div>

    <div class="row">
      <ul>
        <li><a href="#">Contact us</a></li>
        <li><a href="#">Our Services</a></li>
        <li><a href="#">Privacy Policy</a></li>
        <li><a href="#">Terms & Conditions</a></li>
        <li><a href="#">Career</a></li>
      </ul>
    </div>

    <div class="row">
      <div>
        Copyright © 2023 CoWrite - All rights reserved
      </div>
    </div>
  </div>
</footer>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <h5 class="cowrite">CoWrite</h5>
      <%= image_tag "cowrite_logo_txt.png" %>
    <% end %>


    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="navbar-brand-center">
      <%= link_to root_path do %>
        <%= image_tag "cowrite_logo1.png" %>
      <% end %>
    </div>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <%# <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link"
          </li> %>
          <li class="nav-item-un">
            <%= link_to current_user.first_name, profile_path(current_user.id), class:"user-name" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <% if current_user.photo.attached? %>
            <%= cl_image_tag current_user.photo.key, height: 40, width: 40, crop: :fill, style:"border-radius: 50%;" %>
            <% else %>
             <%= image_tag "blankprofile.png", class: "avatar", alt: "dropdown menu" %>
            <% end %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "My profile", profile_path(current_user.id), class: "dropdown-item" %>
              <%# <%= link_to "Settings?", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/stories/_form.html.erb
<div class="container-form">
  <div class="container-add">
      <div class="text">
        <h3 class="new">Add a new Story</h3>
      </div>
    <%= simple_form_for story do |f| %>
    <%= f.input :photos, as: :file, input_html: { class: "picture",multiple: true },label_html: {class:"label"} %>
    <%= f.input :title,  input_html:{class: "addstory"}, label_html: {class:"label"} %>
    <%# <%= f.input :genre,  input_html:{class: "addstory"}, label_html: {class:"label"} %>
    <%= f.association :category,  input_html:{class: "addstory"}, label_html: {class:"label"} %>
    <%= f.input :synopsis,  input_html:{class: "addstory"}, label_html: {class:"label"} %>
    <%= f.rich_text_area :rich_content %>
    <%= f.submit "Add a New Story", class: "btn btn-primary"%>
    <% end %>
  </div>
</div>

app/views/stories/index.html.erb
<div class="all-container-index">
  <h1>All stories</h1>
    <div class="index-container">
      <div class="all-container">
        <div class="search-wrapper">
          <%= form_with url: stories_path, method: :get, class: "d-flex" do %>
            <%= text_field_tag :query,
                params[:query],
                class: "form-control",
                placeholder: "Discover a story..."
            %>
          <%= submit_tag "Search", name: "", class: "btn-search" %>
        <% end %>
        </div>
        </div>
        <div class="all-stories-idx">
          <div class="index-card">
            <% @stories.each do |story| %>
                <div class="card-info p-3">
                  <a href="<%= story_path(story.id)%>" class="i">
                    <%= cl_image_tag story.photos.first.key, alt:"story image", class: "index-card-image" %>
                    <div class="story-index-info">
                      <h3 class="font-weight-bold h3"><%= story.title %></h3>
                      <h5 class="font-weight-bold h5"><%= story.synopsis %></h5>
                    </div>
                  </div>
              </a>
          <% end %>
        </div>
    </div>
</div>

app/views/stories/new.html.erb
<%= render "form", story: @story %>

app/views/stories/show.html.erb
<div class="ssc">
  <div class="ssc-content">
    <div class="story-info-sp">
      <h6>Genre : <%= @story.genre %></h6>
      <h6><%= @story.get_upvotes.size   %> Likes</h6>
      <h6><%= @story.get_downvotes.size %> Dislikes</h6>
    </div>
    <h1><strong><%= @story.title %></strong></h1>
    <h6><%= @story.synopsis %></h6>
    <% @story.photos.each do |photo| %>
      <%= cl_image_tag photo.key, height: 300, width: 400, crop: :fill, radius: 5 %>
    <% end %>
    <h6><strong> Started by: </strong><%= link_to "#{@story.user.first_name} #{@story.user.last_name}" , profile_path(@story.user)  %></h6>

    <div class="likes-un">
      <%= button_to like_story_path(@story), method: :put do %>
      <i class="fa fa-thumbs-up" style="font-size20px;color:black"></i>
        <%= @story.get_upvotes.size %>
      <% end %>

      <%= button_to unlike_story_path(@story), method: :put do %>
        <i class="fa fa-thumbs-down" style="font-size20px;color:black"></i>
        <%= @story.get_downvotes.size %>
      <% end %>
    </div>

    <p><%= @story.content %></p>
    <p><%= @story.rich_content %></p>

    <% @story.collabs.each do |collab| %>
    <h5> Collab By: <%= link_to "#{collab.user.first_name} #{collab.user.last_name}" , profile_path(collab.user)  %></h5>
      <li class="list-group-item"><%= collab.rich_content %>
      </li>
      <% end %>
    <div data-controller ="toggle">
      <button class="btn btn-primary mt-4" data-action="click-> toggle#fire">Continue this Story</button>

       <div class="mt-3 d-none"data-toggle-target="toggleableElement">
            <%= simple_form_for [@story,@collab] do |f| %>
            <%= f.rich_text_area :rich_content,  wrapper_html:{class: "test"}%>
            <%= f.submit "Add a Collab", class: "btn btn-primary"%>
              <% end %>
        </div>
   </div>

  <div class="form-container" data-controller ="toggle">
      <button class="btn btn-primary mt-4" data-action="click-> toggle#fire">Add a Review</button>
     <div class="mt-3 d-none"data-toggle-target="toggleableElement">
          <%= simple_form_for [@story, @review] do |f| %>
            <%= f.input :comment, input_html:{class: "test"}, label_html: {class:"label"}%>
            <%= f.submit "Submit review", class: "btn btn-primary" %>
           <% end %>
      </div>
  </div>

  <div class="review">
    <ul class="list-group">
      <% @story.reviews.each do |review| %>
      <h5> By: <%= link_to "#{review.user.first_name} #{review.user.last_name}" , profile_path(review.user)  %></h5>
        <li class="list-group-item"><%= review.comment %> </li>
      <% end %>
    </ul>
  </div>






   <% if @story.user == current_user %>
    <%= link_to "Delete",
      story_path(@story),
      data: {turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
   <% end %>
    <p><a class="btn btn-primary" href="<%= stories_path %>">Stories index</a></p>
    <br>
  </div>
</div>